groups:
  - name: nginx-alerts
    rules:
      - alert: NginxHighRequestRate
        expr: nginx_http_requests_total > nginx_http_requests_total * 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Nginx Request Rate"
          description: "The Nginx request rate has exceeded 10% of the average request rate over the last minute."

