groups:
  - name: nginx-alerts
    rules:
      - alert: NginxHighRequestRate
        expr: nginx_http_requests_total > 50
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Nginx Request Rate"
          description: "The Nginx request rate has exceeded the threshold of 100 requests per minute."

